export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";

export const SET_LOADING = "SET_SEARCH_LOADING";

export const UPDATE_PUB_SEARCH = "UPDATE_PUB_SEARCH";
export const PUB_SEARCH_ERROR = "PUB_SEARCH_ERROR";
export const ADD_NEXT_PAGE_RESULTS = "ADD_NEXT_PAGE_RESULTS";

export const UPDATE_DISCUSS_SEARCH = "UPDATE_DISCUSS_SEARCH";
export const DISCUSS_SEARCH_ERROR = "DISCUSS_SEARCH_ERROR";

export const SET_ITEM_LOADING = "SET_ITEM_LOADING";
export const ITEM_ERROR = "ITEM_ERROR";
export const UPDATE_ITEM = "UPDATE_ITEM";

export const UPDATE_DISCUSSION = "UPDATE_DISCUSSION";

export const SEND_ERROR = "SEND_ERROR";
